- name: Install nginx
  apt: pkg=nginx state=latest
- name: '/etc/nginx/sites-enabled/default: remove'
  file: path=/etc/nginx/sites-enabled/default state=absent
- name: 'Install mail vhost'
  template: src=roles/nginx/templates/mail.j2 dest=/etc/nginx/sites-available/mail
- name: '/etc/nginx/sites-enabled/mail'
  file: src=/etc/nginx/sites-available/mail dest=/etc/nginx/sites-enabled/mail state=link
- name: '/etc/nginx/nginx.conf remove all ssl_ params'
  lineinfile: dest=/etc/nginx/nginx.conf regexp="^[\s#]*ssl_" state=absent
- name: '/etc/nginx/conf.d/ssl.conf'
  template: src=roles/nginx/templates/ssl.conf.j2 dest=/etc/nginx/conf.d/ssl.conf
- name: '/etc/nginx/extra'
  shell: mkdir -p /etc/nginx/extra
- name: '/etc/nginx/extra/security'
  template: src=roles/nginx/templates/security.j2 dest=/etc/nginx/extra/security
- name: 'enable HPKP'
  shell: echo "add_header Public-Key-Pins 'pin-sha256=\"$(openssl x509 -in /etc/ssl/certs/this-machine.pem -pubkey -noout | openssl rsa -pubin -outform der | openssl dgst -sha256 -binary | base64)\"; pin-sha256=\"{{ nginx.hpkp_sha256 }}\"; max-age=2592000';" >> /etc/nginx/extra/security
  when: nginx.hpkp_sha256
- name: 'blacklist.conf'
  template: src=roles/nginx/templates/blacklist.conf.j2 dest=/tmp/blacklist.conf
- name: 'blockips.conf'
  template: src=roles/nginx/templates/blockips.conf.j2 dest=/tmp/blockips.conf
- name: 'blacklist.conf install'
  shell: 'curl -f -o /etc/nginx/conf.d/blacklist.conf https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/blacklist.conf || cp /tmp/blacklist.conf /etc/nginx/conf.d/blacklist.conf'
- name: 'blockips.conf install'
  shell: 'curl -f -o /etc/nginx/conf.d/blockips.conf https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/blockips.conf || cp /tmp/blockips.conf /etc/nginx/conf.d/blockips.conf'
